version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "MyCSFdb"
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_password"
    ports:
      - "5435:5432"
    container_name: MyCSF  